### ISSUE TITLE
Warning when precompiling assets

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#186] opened 2017-04-08 12:45 UTC
I get this warning when precompiling assets for `v2.1.2` our recommended version:

```sh
autoprefixer: myjobs/app/assets/stylesheets/application.css.scss:10602:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
autoprefixer: myjobs/app/assets/stylesheets/application.css.scss:10622:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
```

It doesn't break anything that I notice, but would be nice to resolve.

**Comment by brianmcmichael** [comment] 2017-04-10 02:50
This is already in a PR

https://github.com/OSC/ood-myjobs/pull/181

**Comment by brianmcmichael** [comment] 2017-04-10 13:12
Duplicate of #180

**Closed by brianmcmichael** 2017-04-10 13:12 UTC
Labels: enhancement
